name: 'PR Dependency Check'
description: 'Verify PR dependencies are merged or closed'
id: pr-dependencies-action
branding:
  icon: alert-triangle
  color: orange
runs:
  using: node20
  main: 'dist/index.js'
