on: [ pull_request, workflow_dispatch ]

jobs:
  self_test_job:
    runs-on: ubuntu-latest
    name: self test
    steps:
      - uses: actions/checkout@v2
      - name: check dependencies
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
